var username=("Raffay sharjeel")
alert(username)
var message=("Hellow world")
alert(message)
var name=("jhone Doe")
alert(name)
var age=("15 years old")
alert(age)
var education=("mobile app and web development")
alert(education)
alert(
    "pizza \n pizz \n piz \n pi \n p"
)
var email=( "my email address is  "+  "raffaysharjeel@gmail.com")
alert( email )
var book =(" A samarter way to learn javascript")
alert("i am trying to learn from " + book)
document.write("yeh i can  write html content through javascript ")
var symbol=("“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬” ")
alert(symbol)